name: 💰 Evening Finance
on:
  schedule:
    - cron: '30 10 * * *' # 台灣 18:30
  workflow_dispatch:
jobs:
  run_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install requests feedparser google-generativeai
      - name: Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python daily_intel.py --mode finance
      - name: Commit
        run: |
          git config --global user.name "Action Bot"
          git config --global user.email "bot@github.com"
          git add finance_log.md portfolio.json || true
          git commit -m "💰 Portfolio Update" || echo "No changes"
          git push