name: 📈 Morning Forecast
on:
  schedule:
    - cron: '30 0 * * *' # 台灣 08:30
  workflow_dispatch:
jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install requests feedparser google-generativeai
      - name: Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python daily_intel.py --mode morning